package com.bean;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsname
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.myorderid
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    private Integer myorderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsname
     *
     * @return the value of goods.goodsname
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsname
     *
     * @param goodsname the value for goods.goodsname
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.myorderid
     *
     * @return the value of goods.myorderid
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    public Integer getMyorderid() {
        return myorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.myorderid
     *
     * @param myorderid the value for goods.myorderid
     *
     * @mbggenerated Fri Nov 09 11:23:08 CST 2018
     */
    public void setMyorderid(Integer myorderid) {
        this.myorderid = myorderid;
    }
}