package com.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import com.bean.Goods;

@Repository
public interface GoodsMapper {

	List<Goods> selectAllGoods();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbggenerated Fri Nov 09 11:23:08 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbggenerated Fri Nov 09 11:23:08 CST 2018
	 */
	int insert(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbggenerated Fri Nov 09 11:23:08 CST 2018
	 */
	int insertSelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbggenerated Fri Nov 09 11:23:08 CST 2018
	 */
	Goods selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbggenerated Fri Nov 09 11:23:08 CST 2018
	 */
	int updateByPrimaryKeySelective(Goods record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table goods
	 *
	 * @mbggenerated Fri Nov 09 11:23:08 CST 2018
	 */
	int updateByPrimaryKey(Goods record);
}